language: python
before_install:
- sudo apt-get install -qq libxml2-dev libxslt-dev
env:
- CFLAGS="-O0"
python:
- 2.7
- 3.5
- 3.6
install:
- pip install --upgrade pip
- pip install coveralls
- pip install .
script:
- python test.py
